### ISSUE TITLE
FileNotFoundError: with ms2pip

### ISSUE THREAD

**Issue by JesusCastano01** [QuantSysBio/inSPIRE#31]
Hi,

I was trying to run Inspire using ms2pip instead of Prosit, but I ran into an issue that I'm not sure how to solve. The software is supposed to generate the file ms2pipInput.preprec to start ms2pip,  but for some reason is not doing it.

![image](https://github.com/QuantSysBio/inSPIRE/assets/139022774/1464abbe-be34-4d4b-bffd-9b89988c1c9b)

This is what the config file looks like, in case it's useful:

![image](https://github.com/QuantSysBio/inSPIRE/assets/139022774/d35f78c1-a7e7-4bbc-9e83-72c1bd048815)

I'd appreciate any suggestion to solve this problem.
Thanks,

**Comment by jamc1996** [comment]
Hello,

Thanks for using inSPIRE! I think the problem may be the inSPIRE version, so I would suggest you run

```
pip install inspirems==1.0
```

to get the version you need.

We have more limited MS2PIP support for the latest versions of inSPIRE as we are mostly focussing on using Prosit, I updated the README now so that you can see more clearly which versions to install:

https://github.com/QuantSysBio/inSPIRE/commit/75e1f2e4712050aa3a839814edad4ea2e45c1e1e

Let me know if you still have problems, we can release a patch version if needed.

Best wishes,
John.

**Comment by jamc1996** [comment]
Closing this issue, if anybody reading this still has the above issue after using my suggestion above please re-open or open a new issue 👍
